### ISSUE TITLE
vsmeta2nfo request

### ISSUE THREAD

**Issue by ChilliNr1** [oPromessa/imdb2vsmeta#1]
Hi,
is it possible for you to design a program that converts from vsmeta to nfo, please?
Since the Video Station is no longer supported from Synology it would be great to use the metadata for Jellyfin.
Thank you!

**Comment by oPromessa** [comment]
That's true. I've deployed Emby on the Synology and he is sourcing all the metadata from the web. 

Have you tried it?

Do you have custom edited metadata on the vsmeta files ?

**Comment by ChilliNr1** [comment]
No, I just tried Jellyfin so far. It worked ok on the series and movies.
But yes I've some movies, especially adult stuff, with custom metadata (Cover/Backdrop).
Is it possible to extract the data from the vsmeta file?

**Comment by oPromessa** [comment]
@ChilliNr1 . Don't know if I'll have the time.

### But thought of the following alternative: if you use the --check option to check vsmeta files in a folder, the tool will show you basic info you can then use to build your NFO. 

* Please note it will also create **in the current folder** JPGs files for the backdrop, poster_01 and poster info available in the .vsmeta file.

Example:

```py
$ python imdb2vsmeta.py --movies --check working/Info
-------------- : Checking file [/XXX/working/Info/American Beauty (1999).mpg.vsmeta]
Title          : American Beauty
Title2         : American Beauty
Episode title  : American Beauty
Episode year   : 1999
Episode date   : 1999-10-01
Episode locked : False
TimeStamp      : 1732835787
Classification : R
Rating         : 8.3
Summary        : A sexually frustrated suburban father has a mid-life crisis after becoming infatuated with his daughter's best friend.
Cast           : Kevin Spacey, Annette Bening, Thora Birch,
Director       : Sam Mendes,
Writer         : Alan Ball, 
Genre          : Drama, 
Episode Meta  :
null
TV Show Season : 00
TV Show Episode: 00
$ ls -l *jpg
196541838 1008 -rw-r--r--  1 XXX  staff   501K Nov 28 23:24 American Beauty (1999).mpg.vsmeta_back_drop.jpg
196541839 1008 -rw-r--r--  1 XXX  staff   501K Nov 28 23:24 American Beauty (1999).mpg.vsmeta_poster_01.jpg
196541494 1008 -rw-r--r--  1 XXX  staff   501K Nov 28 23:16 American_Beauty_(_poster.jpg
```

### Also take a look at [nfoeditor](https://github.com/oPromessa/nfoeditor) which may be helpful as it: "Takes a XLS database with NFO tags for your HomeVideo files and generate corresponding NFO files for your KODI Library."
