### ISSUE TITLE
Script seems unable to retrive movie information from imdb

### ISSUE THREAD

**Issue by icodeless** [oPromessa/imdb2vsmeta#2]
Hi there, first, thank you for making this script! Next, can you help me point out what went wrong? I have installed the prerequisites as directed. Thanks in advance!
**Describe the bug**
Unable to find entry for a verified IMDB movie. Staging folder consists 3 movies as shown below.

(venv) admin@server:~$ python imdb2vsmeta.py --search /volume4/docs/Staging/  --verbose  --movies --no-copy
Processing folder: [/volume4/docs/Staging].
filename [{filename}]
Found: [0] entries for Title: [Donald Gets Drafted (] Year: [1942]
No information found for 'Donald Gets Drafted ('
        Processed title [Donald Gets Drafted (] year [1942] vsmeta [None]
filename [{filename}]
Found: [0] entries for Title: [Donald's Penguin (] Year: [1939]
No information found for 'Donald's Penguin ('
        Processed title [Donald's Penguin (] year [1939] vsmeta [None]
filename [{filename}]
Found: [0] entries for Title: [Donald's Snow Fight (] Year: [1942]
No information found for 'Donald's Snow Fight ('
        Processed title [Donald's Snow Fight (] year [1942] vsmeta [None]

**To Reproduce**
1. Just run the script with the intended parameters

**Expected behavior**
Script can at least show if it's able to search movie information from imdb

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Synology DS1522+
 - Browser Chrome
 - Version latest

**Comment by oPromessa** [comment]
@icodeless Glad it may be of use to you. 

I've fixed some of the output reporting. Where it used to show "filename [{filename}]" it should now show "Processing title" and related info.

Thing is that these titles are "short" movies and the tool was filtering only movies. 

The tool now also considers "short". I've added also "tvMovie" ;)

Give it a twirl and let me know!

**Comment by oPromessa** [comment]
@icodeless let me know if it worked for you!
